name: <Native> Linux

on: [push]

env:
  CONAN_USER_HOME : ${{ github.workspace }}/.conan

# github.head_ref is only defined on pull_request events
concurrency:
  group: ${{ github.workflow }}-${{ github.actor }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  compile_linux:
    name: "Linux-Ubuntu"
    if: 
      (! contains(github.event.pull_request.body, '[X] does not change any runtime related code or build configuration'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: actions/setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 11
          platform: x64
      - name: install conan
        run: python -m pip install conan && conan -v
      - name: config clang profile
        run: |
          conan profile new clang
          conan profile update settings.os=Linux clang 
          conan profile update settings.compiler=clang clang
          conan profile update settings.compiler.version=11 clang
          conan profile update settings.arch=x86_64 clang
          conan profile update settings.build_type=Release clang
          conan profile show clang
      - name: install third party
        run: |
          mkdir -p ${{ github.workspace }}/native/conan/build
          cd ${{ github.workspace }}/native/conan/build
          conan install ${{ github.workspace }}/native/conan -pr clang --build=missing -j install_info.json
          ls ${{ github.workspace }}/native/conan/build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gen files
          path: ${{ github.workspace }}/native/conan/build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gen files2
          path: ${{ github.workspace }}/.conan
      #- run: conan profile new default --detect && conan profile show default && conan profile update settings.compiler.libcxx=libstdc++11 default